version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  assistant-service:
    build: ./assistant-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production

  nodejs-chatbot-service:
    build: ./nodejs-chatbot-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  voice-command:
    build: ./voice-command
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
