name: Voice Command Service CI

on:
  push:
    paths:
      - 'voice-command/**'
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd voice-command
          npm install

      - name: Run tests
        run: |
          cd voice-command
          npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "klodinklod12"
          password: "dckr_pat_xfCvZjsQn0uDDM56z10nCVRDTq4"

      - name: Build Docker image
        run: |
          cd voice-command
          docker build -t klodinklod12/voice-command:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push klodinklod12/voice-command:latest

